### ISSUE TITLE
[PE-D] Does not specifically handle exceptions for empty task [TITLE]

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-W11-3/tp#123]
`sat` is a valid input and day of the week and `[TITLE]` parameter is not inputted, however it wrongly recognises the former input as invalid.

![image.png](https://raw.githubusercontent.com/izdiyadfrhn/ped/main/files/ee1c837a-3b71-4c05-9635-78ce5f1e0a00.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: izdiyadfrhn/ped#2

**Comment by richwill28** [comment]
Thanks for pointing this out @izdiyadfrhn. We will try to improve error messages on v2.1.
