### ISSUE TITLE
[PE-D] UG formatting issues

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-W11-3/tp#124]
![image.png](https://raw.githubusercontent.com/uosjapuelks/ped/main/files/299bfc75-65c5-403d-8cca-167f9acbb424.png)

some '[' are bolded followed by ']' that is not bolded.

done is bolded for whatever reason it is, set and exit have colour for unknown or not obvious reasons too

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: uosjapuelks/ped#7

**Comment by richwill28** [comment]
A duplicate of #118.
