### ISSUE TITLE
[PE-D] UG module formatting

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-W11-3/tp#127]
![image.png](https://raw.githubusercontent.com/uosjapuelks/ped/main/files/2eb59b21-4f96-484c-ad71-868f0b4a09b0.png)

Almost every 'for' is consistently bolded even in preclusion title and in code when it seems to only be meant for module code.

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: uosjapuelks/ped#10

**Comment by richwill28** [comment]
A duplicate of #118.
