### ISSUE TITLE
[PE-D] Unexpected output for add task function

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-W11-3/tp#130]
![image.png](https://raw.githubusercontent.com/AnShengLee/ped/main/files/caaf816b-cf3d-4b1f-8b09-a6b88c80cb10.png)

I believe the following command should cause an invalid warning. Or the program allows garbage input at the end, if this is the case my mistake.

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: AnShengLee/ped#4

**Comment by richwill28** [comment]
Thanks for pointing this out @AnShengLee. This is definitely a bug from our side.

**Comment by richwill28** [comment]
Note for developer fixing this issue:

An approach mentioned in #133 should probably be sufficient in solving this issue.
