### ISSUE TITLE
[PE-D] Help command not isolated

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-W11-3/tp#132]
![image.png](https://raw.githubusercontent.com/uosjapuelks/ped/main/files/e555548d-fcc0-4b09-9c0e-1a2b501ff58b.png)

When additional information input after help, help still appears

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: uosjapuelks/ped#13

**Comment by richwill28** [comment]
Hmm.. should we add validation for this? @rebchua39 @ptejasv @Roycius
