### ISSUE TITLE
[PE-D] Empty List

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-W11-3/tp#142]
![image.png](https://raw.githubusercontent.com/uosjapuelks/ped/main/files/9f8cefed-939b-4c84-8889-6b0dc0544c3c.png)

-------------
Labels: `severity.High` `type.FeatureFlaw`
original: uosjapuelks/ped#18

**Comment by richwill28** [comment]
Just a UI formatting issue on empty list. A more friendly message would be..

```
There are no tasks in the list.
```
