### ISSUE TITLE
[PE-D] No Edit feature for the Items

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-W11-3/tp#145]
The current application does not give users the opportunity to amend/edit any item they have stored.
However, because of the many subitems allowed to be put in one item (eg. a task can have a name, date, priority, and information). It is likely that the user may not know all the information of all of them at the time he/she is creating this task. Since it is troublesome to delete the previous task and create a new one, it would be good to have an edit/update feature to solve this problem. 

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: WU-LUOYU-SERENA/ped#2

**Comment by richwill28** [comment]
Thanks for the suggestion @WU-LUOYU-SERENA.
