### ISSUE TITLE
[PE-D] ModuleInfo Bug

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-W11-3/tp#148]
![image.png](https://raw.githubusercontent.com/uosjapuelks/ped/main/files/416d8985-e6d7-4156-b29a-3217e17b2816.png)

Still searching for empty module input in the first part of the screenshot

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: uosjapuelks/ped#21

**Comment by richwill28** [comment]
Note for developer fixing this issue:

1. `moduleinfo` does not properly parse invalid inputs.

2. Error messages should also be improved as mentioned in #141.

**Comment by ptejasv** [comment]
Fixed in PR #164
