### ISSUE TITLE
[PE-D] Further clarity required in finding task / lesson by keyword function in UG

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-W11-3/tp#150]
![image.png](https://raw.githubusercontent.com/AnShengLee/ped/main/files/0b5a2d5f-e368-4774-826c-a07a407cec64.png)

Tried to find by priority or day but it is not possible, cause it can be done from list function. I believe the UG has to be clearer for this. 

![image.png](https://raw.githubusercontent.com/AnShengLee/ped/main/files/242d1f01-4ec3-4be7-ad8d-0077c8a7a2ac.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: AnShengLee/ped#9

**Comment by richwill28** [comment]
This is not a bug. Filtering by priority is done using `list task {PRIORITY}`, which is specified in the UG.
