### ISSUE TITLE
[PE-D] Lesson disappeared just like how task disappeared

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-W11-3/tp#153]
![image.png](https://raw.githubusercontent.com/uosjapuelks/ped/main/files/ab10a014-3c6c-44a3-abb1-951b870dedaa.png)

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: uosjapuelks/ped#23

**Comment by richwill28** [comment]
A duplicate of #134.
