### ISSUE TITLE
[PE-D] Listing of Lessons Not in Chronological Order

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-W11-3/tp#156]
## Problem

The list feature for lessons are not in chronological order of the lessons but rather the chronological order of the input time.

![Screenshot 2021-10-29 at 5.40.17 PM.png](https://raw.githubusercontent.com/WU-LUOYU-SERENA/ped/main/files/81cf8c16-6b54-46a5-a963-3d60d0a00802.png)

## Suggestion

List the lessons in chronological order the lesson time instead. (eg. in the screenshot above, the order should be `movie lesson`, `coding camp`, `violin class`, `piano class`.)

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: WU-LUOYU-SERENA/ped#4

**Comment by richwill28** [comment]
This is not a bug. Just a feature that has yet to be developed.
