### ISSUE TITLE
Duplicate items should not be possible

### ISSUE THREAD

**Issue by richwill28** [AY2122S1-CS2113T-W11-3/tp#160]
I think from a design perspective, adding duplicate lesson and module shouldn't be possible. However. doing duplicate task should be fine.

Any thoughts on this? @rebchua39 @ptejasv @Roycius 

Also, I believe our program currently does not handle duplicate `add module` right?

**Comment by ptejasv** [comment]
I can work the module duplicate part so that `add module` doesn't allow duplicates. I don't think it makes sense to add a module twice.
