### ISSUE TITLE
Wrong URL to Roycius portfolio

### ISSUE THREAD

**Issue by richwill28** [AY2122S1-CS2113T-W11-3/tp#185]
On `AboutUs.md`..

![Capture (3)](https://user-images.githubusercontent.com/69445142/140678686-b19701d3-8c76-4f9b-88e9-9d7cd230e714.png)

Clicking the link above will redirect user to https://ay2122s1-cs2113t-w11-3.github.io/tp/team/Roycius.html. The correct link should be https://ay2122s1-cs2113t-w11-3.github.io/tp/team/roycius.html. (Notice the lowercase)

**Comment by Roycius** [comment]
I have fixed this while updating my profile picture in PR #187
